= Manual build

.Build dependencies
[source,bash]
....
apt install -y git ninja-build cmake clang libboost-locale-dev libboost-thread-dev libboost-filesystem-dev libboost-log-dev libboost-stacktrace-dev libssl-dev libgstreamer1.0-dev  libgstreamer-plugins-base1.0-dev libevdev-dev libdrm-dev libpci-dev libinput-dev libxkbcommon-dev libgbm-dev libpulse-dev libcurl4-openssl-dev
....

Install Rust following the https://www.rust-lang.org/tools/install[official docs] or avoid building our custom compositor by passing `-DLINK_RUST_WAYLAND=OFF` to cmake.

.Compile
[source,bash]
....
cmake -Bbuild -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=17 -DCMAKE_CXX_EXTENSIONS=OFF -G Ninja
ninja -C build
....

If compilations completes correctly you can already start Wolf; in order to successfully streaming you'll probably need to install some Gstreamer plugins first:

.Install gstreamer plugins
[source,bash]
....
apt install -y gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-ugly gstreamer1.0-plugins-bad
....

[WARNING]
====
Based on your system you'll also need some specific plugins in order to enable HW acceleration.
For Intel/AMD you'll need https://gstreamer.freedesktop.org/documentation/vaapi/index.html?gi-language=c[`vaapi`]; Nvidia instead will need https://gstreamer.freedesktop.org/documentation/nvcodec/index.html?gi-language=c[`nvcodec`].

If your package manager doesn't include them you can build them from scratch by following the instructions used in our https://github.com/games-on-whales/wolf/blob/stable/gstreamer.Dockerfile[gstreamer.Dockerfile]
====

.Run!
[source,bash]
....
build/src/wolf/wolf
INFO  | Reading config file from: config.toml
WARN  | Unable to open config file: config.toml, creating one using defaults
INFO  | x509 certificates not present, generating...
INFO  | HTTP server listening on port: 47989
INFO  | HTTPS server listening on port: 47984
....
