#!/usr/bin/env bash
# nixos.sh -- Wolf deployment on NixOS
#
# Sourced by wolf.sh. Requires common.sh to be loaded first.
#
# Unlike other environment scripts, this does NOT imperatively deploy Wolf.
# NixOS is declarative: changes outside of Nix configuration are lost on
# rebuild. Instead, this script generates a NixOS module (wolf.nix) that
# the user imports into their system configuration.

# =========================================================================
# Nix module generation
# =========================================================================

_write_nix_module() {
    local render_node="$1" output="$2"
    local is_nvidia=false
    [[ "$SELECTED_VENDOR" == "NVIDIA" ]] && is_nvidia=true

    # --- File header ---
    if $is_nvidia; then
        cat > "$output" <<'NIXEOF'
# wolf.nix -- Wolf cloud gaming NixOS module (NVIDIA)
# Generated by wolf.sh. Import this into your configuration.nix or flake.
#
# NVIDIA setup requires the wolf-nvidia-vol flake for driver volume creation.
# See the instructions printed by wolf.sh, or the README section below.
#
# Flake setup:
#   1. Add to your flake.nix inputs:
#        wolf-nvidia-vol = {
#          url = "github:altano/flakes?dir=wolf-nvidia-vol";
#          inputs.nixpkgs.follows = "nixpkgs";
#        };
#   2. Pass `inputs` to your NixOS module (see nixpkgs wiki on flakes)
#   3. Import this file in your configuration
#   4. Run: sudo nixos-rebuild switch

{ config, pkgs, inputs, ... }:

let
  wolfNvidiaVol = inputs.wolf-nvidia-vol.lib.mkWolfNvidiaVol {
    inherit pkgs;
    nvidiaPackage = config.hardware.nvidia.package;
    # libnvrtc is required by GStreamer's cudaconvertscale element for
    # NVENC hardware encoding. Not included in the driver .run file.
    extraLibs = [ pkgs.cudaPackages.cuda_nvrtc.lib ];
  };
in
NIXEOF
    else
        cat > "$output" <<'NIXEOF'
# wolf.nix -- Wolf cloud gaming NixOS module
# Generated by wolf.sh. Import this into your configuration.nix or flake.
#
# Usage:
#   1. Copy this file alongside your configuration.nix
#   2. Add to your imports: imports = [ ./wolf.nix ];
#   3. Run: sudo nixos-rebuild switch

{ config, pkgs, ... }:

NIXEOF
    fi

    # --- Shared body (static) ---
    cat >> "$output" <<'NIXEOF'
{
  # Enable Docker (used by Wolf to launch game containers)
  virtualisation.docker.enable = true;

  # Persistent directories for Wolf data
  systemd.tmpfiles.rules = [
    "d /etc/wolf 0755 root root -"
    "d /etc/wolf/wolf-den 0755 root root -"
    "d /etc/wolf/covers 0755 root root -"
  ];

NIXEOF

    # --- Udev rules from canonical source ---
    {
        echo "  # Udev rules for Wolf virtual input devices"
        echo "  services.udev.extraRules = ''"
        write_udev_rules_content | sed 's/^/    /'
        echo "  '';"
        echo ""
    } >> "$output"

    # --- OCI container config (needs variable substitution) ---
    local nvidia_env="" nvidia_volumes="" nvidia_devices=""
    if $is_nvidia; then
        nvidia_env='        NVIDIA_DRIVER_VOLUME_NAME = "\${wolfNvidiaVol}";'
        nvidia_volumes='        "\${wolfNvidiaVol}:/usr/nvidia:ro"'
        nvidia_devices='        "--device=/dev/nvidia0"
        "--device=/dev/nvidiactl"
        "--device=/dev/nvidia-modeset"
        "--device=/dev/nvidia-uvm"
        "--device=/dev/nvidia-uvm-tools"'
    fi

    cat >> "$output" <<NIXEOF
  # Wolf OCI containers
  virtualisation.oci-containers.backend = "docker";
  virtualisation.oci-containers.containers = {
    wolf = {
      image = "ghcr.io/games-on-whales/wolf:stable";
      environment = {
        WOLF_RENDER_NODE = "${render_node}";
        XDG_RUNTIME_DIR = "/tmp/sockets";
${nvidia_env:+${nvidia_env}
}      };
      volumes = [
        "/etc/wolf:/etc/wolf:rw"
        "/var/run/docker.sock:/var/run/docker.sock:rw"
        "/dev/:/dev/:rw"
        "/run/udev:/run/udev:rw"
${nvidia_volumes:+${nvidia_volumes}
}      ];
      extraOptions = [
        "--network=host"
        "--device=/dev/dri"
        "--device=/dev/uinput"
        "--device=/dev/uhid"
${nvidia_devices:+${nvidia_devices}
}        "--device-cgroup-rule=c 13:* rmw"
      ];
    };

    wolf-den = {
      image = "ghcr.io/games-on-whales/wolf-den:stable";
      environment = {
        WOLF_SOCKET_PATH = "/tmp/sockets/wolf.sock";
      };
      volumes = [
        "/etc/wolf/wolf-den:/app/wolf-den"
        "/etc/wolf/covers:/etc/wolf/covers"
      ];
      ports = [ "8080:8080" ];
      dependsOn = [ "wolf" ];
    };
  };
}
NIXEOF
}

# =========================================================================
# Main
# =========================================================================

nixos_main() {
    parse_args "$@"

    select_gpu

    local output="${NIXOS_OUTPUT:-./wolf.nix}"

    info "Wolf Cloud Gaming Setup (NixOS)"
    echo "  GPU:    $(selected_gpu_label)"
    echo "  Node:   ${SELECTED_RENDER_NODE}"
    echo "  Output: ${output}"
    echo ""

    _write_nix_module "$SELECTED_RENDER_NODE" "$output"

    info "Generated ${output}"
    echo ""
    echo "--- ${output} ---"
    cat "$output"
    echo "--- end ---"

    local ip; ip=$(get_local_ip)

    # NixOS-specific deploy instructions (not using print_summary since
    # Wolf isn't running yet — user must nixos-rebuild first)
    if [[ "$SELECTED_VENDOR" == "NVIDIA" ]]; then
        cat <<EOF

================================================================
Wolf NixOS module generated: ${output}

  GPU: $(selected_gpu_label)

NVIDIA setup requires two steps:

  Step 1: Add the wolf-nvidia-vol flake input to your flake.nix:

    inputs = {
      wolf-nvidia-vol = {
        url = "github:altano/flakes?dir=wolf-nvidia-vol";
        inputs.nixpkgs.follows = "nixpkgs";
      };
    };

    Make sure 'inputs' is passed to your NixOS modules. For example:

    outputs = { self, nixpkgs, wolf-nvidia-vol, ... }: {
      nixosConfigurations.myhost = nixpkgs.lib.nixosSystem {
        specialArgs = { inherit inputs; };
        modules = [ ./configuration.nix ./wolf.nix ];
      };
    };

  Step 2: Copy wolf.nix and rebuild:

    cp ${output} /etc/nixos/wolf.nix
    sudo nixos-rebuild switch
EOF
    else
        cat <<EOF

================================================================
Wolf NixOS module generated: ${output}

  GPU: $(selected_gpu_label)

To deploy:

  1. Copy wolf.nix to your NixOS configuration directory:

       cp ${output} /etc/nixos/wolf.nix

  2. Add it to your imports in configuration.nix (or flake):

       imports = [ ./wolf.nix ];

  3. Rebuild:

       sudo nixos-rebuild switch
EOF
    fi

    # Shared tail
    cat <<EOF

After rebuild, Wolf will start automatically.

  Wolf:      streaming on ports 47984-48200 (Moonlight)
  Wolf Den:  http://${ip}:8080 (web management)

To pair with Moonlight:
  1. Open Wolf Den at http://${ip}:8080 to manage apps and clients
  2. Open Moonlight and add server: ${ip}
  3. Enter the pairing PIN shown in Moonlight into Wolf Den
================================================================
EOF
}
