#!/usr/bin/env bash
# nixos.sh -- Wolf deployment on NixOS
#
# Sourced by wolf.sh. Requires common.sh to be loaded first.
#
# Unlike other environment scripts, this does NOT imperatively deploy Wolf.
# NixOS is declarative: changes outside of Nix configuration are lost on
# rebuild. Instead, this script generates a NixOS module (wolf.nix) that
# the user imports into their system configuration.

# =========================================================================
# Nix module generation
# =========================================================================

# Generate the base Wolf OCI container config (AMD/Intel).
_write_nix_standard() {
    local render_node="$1" output="$2"

    cat > "$output" <<'NIXEOF'
# wolf.nix -- Wolf cloud gaming NixOS module
# Generated by wolf.sh. Import this into your configuration.nix or flake.
#
# Usage:
#   1. Copy this file alongside your configuration.nix
#   2. Add to your imports: imports = [ ./wolf.nix ];
#   3. Run: sudo nixos-rebuild switch

{ config, pkgs, ... }:

{
  # Enable Docker (used by Wolf to launch game containers)
  virtualisation.docker.enable = true;

  # Udev rules for Wolf virtual input devices
  services.udev.extraRules = ''
    KERNEL=="uinput", SUBSYSTEM=="misc", MODE="0660", GROUP="input", OPTIONS+="static_node=uinput", TAG+="uaccess"
    KERNEL=="uhid", GROUP="input", MODE="0660", TAG+="uaccess"
    KERNEL=="hidraw*", ATTRS{name}=="Wolf PS5 (virtual) pad", GROUP="input", MODE="0660", ENV{ID_SEAT}="seat9"
    SUBSYSTEMS=="input", ATTRS{name}=="Wolf X-Box One (virtual) pad", MODE="0660", ENV{ID_SEAT}="seat9"
    SUBSYSTEMS=="input", ATTRS{name}=="Wolf PS5 (virtual) pad", MODE="0660", ENV{ID_SEAT}="seat9"
    SUBSYSTEMS=="input", ATTRS{name}=="Wolf gamepad (virtual) motion sensors", MODE="0660", ENV{ID_SEAT}="seat9"
    SUBSYSTEMS=="input", ATTRS{name}=="Wolf Nintendo (virtual) pad", MODE="0660", ENV{ID_SEAT}="seat9"
  '';

  # Persistent directories for Wolf data
  systemd.tmpfiles.rules = [
    "d /etc/wolf 0755 root root -"
    "d /etc/wolf/cfg 0755 root root -"
    "d /etc/wolf/wolf-den 0755 root root -"
    "d /etc/wolf/covers 0755 root root -"
    "d /etc/wolf/steam 0755 root root -"
  ];

NIXEOF

    # Inject the render node (not single-quoted, needs variable substitution)
    cat >> "$output" <<NIXEOF
  # Wolf OCI containers
  virtualisation.oci-containers.backend = "docker";
  virtualisation.oci-containers.containers = {
    wolf = {
      image = "ghcr.io/games-on-whales/wolf:stable";
      environment = {
        WOLF_RENDER_NODE = "${render_node}";
        XDG_RUNTIME_DIR = "/tmp/sockets";
        WOLF_CFG_FILE = "/etc/wolf/cfg/config.toml";
        WOLF_DOCKER_SOCKET = "/var/run/docker.sock";
      };
      volumes = [
        "/etc/wolf:/etc/wolf:rw"
        "/var/run/docker.sock:/var/run/docker.sock:rw"
        "/dev/:/dev/:rw"
        "/run/udev:/run/udev:rw"
      ];
      extraOptions = [
        "--network=host"
        "--device=/dev/dri"
        "--device=/dev/uinput"
        "--device=/dev/uhid"
        "--device-cgroup-rule=c 13:* rmw"
      ];
    };

    wolf-den = {
      image = "ghcr.io/games-on-whales/wolf-den:stable";
      environment = {
        WOLF_SOCKET_PATH = "/tmp/sockets/wolf.sock";
      };
      volumes = [
        "/etc/wolf/wolf-den:/app/wolf-den"
        "/etc/wolf/covers:/etc/wolf/covers"
      ];
      ports = [ "8080:8080" ];
      dependsOn = [ "wolf" ];
    };
  };
}
NIXEOF
}

# Generate the NVIDIA Wolf OCI container config.
_write_nix_nvidia() {
    local render_node="$1" output="$2"

    cat > "$output" <<'NIXEOF'
# wolf.nix -- Wolf cloud gaming NixOS module (NVIDIA)
# Generated by wolf.sh. Import this into your configuration.nix or flake.
#
# NVIDIA setup requires the wolf-nvidia-vol flake for driver volume creation.
# See the instructions printed by wolf.sh, or the README section below.
#
# Flake setup:
#   1. Add to your flake.nix inputs:
#        wolf-nvidia-vol = {
#          url = "github:altano/flakes?dir=wolf-nvidia-vol";
#          inputs.nixpkgs.follows = "nixpkgs";
#        };
#   2. Pass `inputs` to your NixOS module (see nixpkgs wiki on flakes)
#   3. Import this file in your configuration
#   4. Run: sudo nixos-rebuild switch

{ config, pkgs, inputs, ... }:

let
  wolfNvidiaVol = inputs.wolf-nvidia-vol.lib.mkWolfNvidiaVol {
    inherit pkgs;
    nvidiaPackage = config.hardware.nvidia.package;
    # libnvrtc is required by GStreamer's cudaconvertscale element for
    # NVENC hardware encoding. Not included in the driver .run file.
    extraLibs = [ pkgs.cudaPackages.cuda_nvrtc.lib ];
  };
in
{
  # Enable Docker (used by Wolf to launch game containers)
  virtualisation.docker.enable = true;

  # Udev rules for Wolf virtual input devices
  services.udev.extraRules = ''
    KERNEL=="uinput", SUBSYSTEM=="misc", MODE="0660", GROUP="input", OPTIONS+="static_node=uinput", TAG+="uaccess"
    KERNEL=="uhid", GROUP="input", MODE="0660", TAG+="uaccess"
    KERNEL=="hidraw*", ATTRS{name}=="Wolf PS5 (virtual) pad", GROUP="input", MODE="0660", ENV{ID_SEAT}="seat9"
    SUBSYSTEMS=="input", ATTRS{name}=="Wolf X-Box One (virtual) pad", MODE="0660", ENV{ID_SEAT}="seat9"
    SUBSYSTEMS=="input", ATTRS{name}=="Wolf PS5 (virtual) pad", MODE="0660", ENV{ID_SEAT}="seat9"
    SUBSYSTEMS=="input", ATTRS{name}=="Wolf gamepad (virtual) motion sensors", MODE="0660", ENV{ID_SEAT}="seat9"
    SUBSYSTEMS=="input", ATTRS{name}=="Wolf Nintendo (virtual) pad", MODE="0660", ENV{ID_SEAT}="seat9"
  '';

  # Persistent directories for Wolf data
  systemd.tmpfiles.rules = [
    "d /etc/wolf 0755 root root -"
    "d /etc/wolf/cfg 0755 root root -"
    "d /etc/wolf/wolf-den 0755 root root -"
    "d /etc/wolf/covers 0755 root root -"
    "d /etc/wolf/steam 0755 root root -"
  ];

NIXEOF

    # Inject the render node (needs variable substitution)
    cat >> "$output" <<NIXEOF
  # Wolf OCI containers
  virtualisation.oci-containers.backend = "docker";
  virtualisation.oci-containers.containers = {
    wolf = {
      image = "ghcr.io/games-on-whales/wolf:stable";
      environment = {
        WOLF_RENDER_NODE = "${render_node}";
        NVIDIA_DRIVER_VOLUME_NAME = "\${wolfNvidiaVol}";
        XDG_RUNTIME_DIR = "/tmp/sockets";
        WOLF_CFG_FILE = "/etc/wolf/cfg/config.toml";
        WOLF_DOCKER_SOCKET = "/var/run/docker.sock";
      };
      volumes = [
        "/etc/wolf:/etc/wolf:rw"
        "/var/run/docker.sock:/var/run/docker.sock:rw"
        "/dev/:/dev/:rw"
        "/run/udev:/run/udev:rw"
        "\${wolfNvidiaVol}:/usr/nvidia:ro"
      ];
      extraOptions = [
        "--network=host"
        "--device=/dev/dri"
        "--device=/dev/uinput"
        "--device=/dev/uhid"
        "--device=/dev/nvidia0"
        "--device=/dev/nvidiactl"
        "--device=/dev/nvidia-modeset"
        "--device=/dev/nvidia-uvm"
        "--device=/dev/nvidia-uvm-tools"
        "--device-cgroup-rule=c 13:* rmw"
      ];
    };

    wolf-den = {
      image = "ghcr.io/games-on-whales/wolf-den:stable";
      environment = {
        WOLF_SOCKET_PATH = "/tmp/sockets/wolf.sock";
      };
      volumes = [
        "/etc/wolf/wolf-den:/app/wolf-den"
        "/etc/wolf/covers:/etc/wolf/covers"
      ];
      ports = [ "8080:8080" ];
      dependsOn = [ "wolf" ];
    };
  };
}
NIXEOF
}

# =========================================================================
# Main
# =========================================================================

nixos_main() {
    parse_args "$@"

    select_gpu

    local output="${NIXOS_OUTPUT:-./wolf.nix}"

    info "Wolf Cloud Gaming Setup (NixOS)"
    echo "  GPU:    $(selected_gpu_label)"
    echo "  Node:   ${SELECTED_RENDER_NODE}"
    echo "  Output: ${output}"
    echo ""

    case "$SELECTED_VENDOR" in
        NVIDIA) _write_nix_nvidia "$SELECTED_RENDER_NODE" "$output" ;;
        *)      _write_nix_standard "$SELECTED_RENDER_NODE" "$output" ;;
    esac

    info "Generated ${output}"
    echo ""
    echo "--- ${output} ---"
    cat "$output"
    echo "--- end ---"

    local ip; ip=$(get_local_ip)

    if [[ "$SELECTED_VENDOR" == "NVIDIA" ]]; then
        cat <<EOF

================================================================
Wolf NixOS module generated: ${output}

  GPU: ${SELECTED_VENDOR} ${SELECTED_NAME} (${SELECTED_DRIVER}) at ${SELECTED_RENDER_NODE}

NVIDIA setup requires two steps:

  Step 1: Add the wolf-nvidia-vol flake input to your flake.nix:

    inputs = {
      wolf-nvidia-vol = {
        url = "github:altano/flakes?dir=wolf-nvidia-vol";
        inputs.nixpkgs.follows = "nixpkgs";
      };
    };

    Make sure 'inputs' is passed to your NixOS modules. For example:

    outputs = { self, nixpkgs, wolf-nvidia-vol, ... }: {
      nixosConfigurations.myhost = nixpkgs.lib.nixosSystem {
        specialArgs = { inherit inputs; };
        modules = [ ./configuration.nix ./wolf.nix ];
      };
    };

  Step 2: Copy wolf.nix and rebuild:

    cp ${output} /etc/nixos/wolf.nix
    sudo nixos-rebuild switch

After rebuild, Wolf will start automatically.

  Wolf:      streaming on ports 47984-48200 (Moonlight)
  Wolf Den:  http://${ip}:8080 (web management)

To pair with Moonlight:
  1. Open Wolf Den at http://${ip}:8080 to manage apps and clients
  2. Open Moonlight and add server: ${ip}
  3. Enter the pairing PIN shown in Moonlight into Wolf Den
================================================================
EOF
    else
        cat <<EOF

================================================================
Wolf NixOS module generated: ${output}

  GPU: ${SELECTED_VENDOR} ${SELECTED_NAME} (${SELECTED_DRIVER}) at ${SELECTED_RENDER_NODE}

To deploy:

  1. Copy wolf.nix to your NixOS configuration directory:

       cp ${output} /etc/nixos/wolf.nix

  2. Add it to your imports in configuration.nix (or flake):

       imports = [ ./wolf.nix ];

  3. Rebuild:

       sudo nixos-rebuild switch

After rebuild, Wolf will start automatically.

  Wolf:      streaming on ports 47984-48200 (Moonlight)
  Wolf Den:  http://${ip}:8080 (web management)

To pair with Moonlight:
  1. Open Wolf Den at http://${ip}:8080 to manage apps and clients
  2. Open Moonlight and add server: ${ip}
  3. Enter the pairing PIN shown in Moonlight into Wolf Den
================================================================
EOF
    fi
}
