= Configuration

Wolf is configured via a TOML config file and some additional optional ENV variables

== ENV variables

* *LOG_LEVEL*: controls the log level, defaults to `INFO`
* *CFG_FILE*: path to the TOML config file, defaults to `config.toml`
* *GST_DEBUG*: Gstreamer debug print, see https://gstreamer.freedesktop.org/documentation/tutorials/basic/debugging-tools.html?gi-language=c[debugging-tools].

== TOML file

The TOML configuration file is read only once at startup (or created if not present) and it'll be modified by Wolf when a new user is successfully paired.

.Default TOML configuration file
[source,toml]
....
paired_clients = [] #<1>
hostname = "wolf"   #<2>
support_hevc = false #<3>
uuid = "0f75f4d1-e28e-410a-b318-c0579f18f8d1" #<4>


[[apps]] #<5>
title = "Test ball"
support_hdr = false

[gstreamer] #<6>

[gstreamer.audio]
default_source = "audiotestsrc wave=ticks is-live=true"
default_audio_params = """
audioconvert ! audiorate ! audioresample ! audio/x-raw, \
channels={channels}\
"""
default_opus_encoder = """
opusenc bitrate={bitrate} bitrate-type=cbr frame-size={p\
acket_duration} bandwidth=fullband audio-type=generic ma\
x-payload-size=1400\
"""
default_sink = """
rtpmoonlightpay_audio name=moonlight_pay packet_duration={packet_duration} encrypt={encrypt} aes_key="{aes_key}" aes_iv="{aes_iv}"  ! udpsink host={client_ip} port={client_port}\
"""

[gstreamer.video]
default_source = "videotestsrc pattern=ball is-live=true"
default_video_params = """
videoscale ! videoconvert ! videorate ! video/x-raw, wid\
th={width}, height={height}, framerate={fps}/1,format=I4\
20, chroma-site={color_range}, colorimetry={color_space}\
"""
default_hevc_encoder = """
x265enc tune=zerolatency speed-preset=superfast bitrate={bitrate} option-string="info=0:keyint=-1:qp=28:repeat-headers=1:slices={slices_per_frame}:frame-threads={slices_per_frame}:aud=0:annexb=1:log-level=3:open-gop=0:bframes=0:intra-refresh=0" ! video/x-h265, profile=main, stream-format=byte-stream\
"""
default_h264_encoder = """
x264enc pass=qual tune=zerolatency speed-preset=superfast b-adapt=false bframes=0 ref=1 bitrate={bitrate} aud=false sliced-threads=true threads={slices_per_frame} option-string="slices={slices_per_frame}:keyint=infinite:open-gop=0" ! video/x-h264, profile=high, stream-format=byte-stream\
"""
default_sink = """
rtpmoonlightpay_video name=moonlight_pay payload_size={payload_s\
ize} fec_percentage={fec_percentage} min_required_fec_packets={m\
in_required_fec_packets} ! udpsink host={client_ip} port={client\
_port}\
"""

....

<1> *paired_clients*: a list of all the Moonlight clients that have succesfully completed the pairing process; it'll be populated by Wolf and saved to this file.

<2> *hostname*: this is the name that will be displayed in the list of hosts in the Moonlight UI

<3> *support_hevc*: when set to `true` will enable support for HEVC in Moonlight

<4> *uuid*: a randomly generated UUID, it's used by Moonlight to know if the current host has already been paired

<5> *apps*: the list of apps that will be seen in Moonlight

<6> *gstreamer*: here are all the default parts that compose the two video and audio pipelines.

== Defining apps

Apps defined here will be shown in Moonlight after successfully pairing with Wolf. +
You can re-define parts of the Gstreamer pipeline easily, ex:

[source,toml]
....
[[apps]]
title = "SMPTE"

[apps.video]
source = "videotestsrc pattern=smpte is-live=true"
....

See more examples in the xref:gstreamer.adoc[] page.