= Troubleshooting

[TIP]
====
When something doesn't work it'll be helpful to be able to see the logs from Wolf, please change the env variable `WOLF_LOG_LEVEL` to `DEBUG` and try to replicate the issue.
====

== Black screen in Moonlight

If it's the very first time that you are running an app, and you can only see a black screen with a cursor in Moonlight, it's probably because Wolf is downloading the corresponding docker image and installing first time updates (when necessary).

If this persists or Moonlight kicks you out of the streaming session then you should probably take a look at the Wolf logs to gather more informations.

=== Vulkan errors in App

Example log line:

....
vulkan: physical device 10de:1c03 compute queue doesn't support presenting on our surface, using graphics queue
vulkan: selecting physical device 'NVIDIA GeForce GTX 1060 6GB': queue family 0
vulkan: physical device supports DRM format modifiers
vulkan: vkCreateDevice failed (VkResult: -7)
Failed to initialize Vulkan
....

Vulkan errors are generally related to the video drivers.

.Nvidia GPU checklist
[%collapsible]
====

Make sure to follow all the instructions on the xref:user:quickstart.adoc[] page.
Here's a brief summary of things to check:

* Check that the nvidia volume driver has been created...
[source,bash]
....
docker volume ls | grep nvidia-driver

local     nvidia-driver-vol
....

* ...and that the same volume name is passed in the env variable `NVIDIA_DRIVER_VOLUME_NAME`

* Make sure that the `nvidia-drm` module has been loaded...
[source,bash]
....
sudo dmesg | grep nvidia-drm    # Should print something like the following:
[   12.561107] [drm] [nvidia-drm] [GPU ID 0x00000100] Loading driver
[   14.138312] [drm] Initialized nvidia-drm 0.0.0 20160202 for 0000:01:00.0 on minor 0
....

* ...and check that the module is loaded with the flag `modeset=1`.
[source,bash]
....
sudo cat /sys/module/nvidia_drm/parameters/modeset
Y
....


====

== Address already in use

You'll see something like the following log lines:

....
terminate called after throwing an instance of 'boost::wrapexcept<boost::system::system_error>'
  what():  bind: Address already in use
INFO  | Received interrupt signal 6, clean exit
....

This means that some other process is using the same ports that Wolf needs in order to communicate with Moonlight.

[TIP]
====
Have you left Sunshine running in the background?
====

The following ports need to be available in order for Wolf to work:

* 47984/tcp - HTTPS
* 47989/tcp - HTTP
* 47998/udp - Video
* 47999/udp - Control
* 48000/udp - Audio
* 48010/tcp - RTSP

== Unable to recognise GPU vendor

Example log line:

....
WARN  | Unable to recognise GPU vendor: red hat, inc.
....

Do you have multiple GPUs installed (or even just a virtual display in a VM)? +
Checkout the xref:user:configuration.adoc#_multiple_gpu[Multiple GPU configuration page]