name: Build docs
on:
  push:
    paths:
      - "docs/**"
  pull_request:
    paths:
      - "docs/**"

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Fire event
        # see docs here: https://docs.github.com/en/rest/actions/workflows?apiVersion=2022-11-28#create-a-workflow-dispatch-event
        run: |
          curl -L \
            --fail-with-body \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GHCR_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/games-on-whales/games-on-whales.github.io/dispatches \
            -d '{"event_type":"trigger-publish"}'
