name: Run clang-format Linter

on:
  push:
    paths-ignore:
      - "docs/**"
      - "docker/**"
      - ".github/**"
  pull_request:
    paths-ignore:
      - "docs/**"
      - "docker/**"
      - ".github/**"

jobs:
  build:
    # Avoid workflows to run twice for PRs (https://github.com/orgs/community/discussions/57827)
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: DoozyX/clang-format-lint-action@v0.14
        with:
          source: 'src'
          exclude: 'src/rust'
          extensions: 'h,hpp,cpp,c'
          clangFormatVersion: 18
          inplace: ${{ github.event_name == 'push' }}

      - uses: EndBug/add-and-commit@v9
        if: github.event_name == 'push'
        with:
          committer_name: GitHub Actions
          committer_email: actions@github.com
          message: 'Committing clang-format changes'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}